apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-pvc
spec:
  accessModes:
    - ReadWriteMany # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 1Gi # volume size requested
#  storageClassName: immediate