version: '3.2'
#volumes:
#   prometheus_data: {}
services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: prometheus
    volumes:
      #- ./config:/etc/prometheus
      - ./data:/prometheus
     # - type: bind
     #   source: ./static/prometheus.yml
     #   target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
 default:
  external:
   name: ms-chassis-nw