--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: rabbitmqw
    version: v1
  name: rabbitmqw
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: rabbitmqw
      version: v1
  template: 
    metadata: 
      labels: 
        app: rabbitmqw
        version: v1
    spec: 
      containers: 
        - 
          image: "rabbitmq:3.6.0-management"
          imagePullPolicy: IfNotPresent
          name: rabbitmqw 
          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "secret string"
            - name: RABBITMQ_NODENAME
              value: "rabbitmq-worker"
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config
      volumes:
       - name: rabbitmq-config
         hostPath:
            path: /etc/rabbitmq #Map it in host VM first
            type: DirectoryOrCreate