version: '2.2'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: jenkins
    cpu_percent: 10
    mem_reservation: 100m
    ports:
      - "8900:8080"
      - "50000:50000"
      #  published: "9094-9096"
      #  protocol: tcp
        #mode: host
    environment:
      HOSTNAME_COMMAND: "echo $$HOSTNAME"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
networks:
 default:
  external:
   name: ms-chassis-nw