--- 
apiVersion: apps/v1
kind: Deploymentz
metadata: 
  labels: 
    app: rabbitmq
    version: v1
  name: rabbitmq
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: rabbitmq
      version: v1
  template: 
    metadata: 
      labels: 
        app: rabbitmq
        version: v1
    spec: 
      containers: 
        - 
          image: "rabbitmq:3-management"
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports: 
          - containerPort: 15672
          - containerPort: 5672
          - containerPort: 4369
          - containerPort: 5671
          - containerPort: 15671
          - containerPort: 25671          

          env:
            - name: RABBITMQ_ERLANG_COOKIE
              value: "secret string"
            - name: RABBITMQ_NODENAME
              value: "rabbitmq-master"
          volumeMounts:
            - mountPath: /etc/rabbitmq
              name: rabbitmq-config
      volumes:
       - name: rabbitmq-config
         hostPath:
            path: config
            type: DirectoryOrCreate